package com.carriloutdoor.comparadorcsvproductos.config;

public class ConstantesNormalizacion {
    public  static final String[][] COLORES = {
            {"CAMUFLAJE/PIXEL FOREST", "CAMUFLAJE/PIXEL FOREST"},
            {"CAMUFFLAJE/PIXEL FOREST", "CAMUFLAJE/PIXEL FOREST"},
            {"CAMUFLAJE PIXELADO", "CAMUFLAJE/PIXEL FOREST"},
            {"COLOR PIXEL FOREST", "CAMUFLAJE/PIXEL FOREST"},
            {"PIXEL FOREST", "CAMUFLAJE/PIXEL FOREST"},

            {"CAMUFLAJE/CAMO FOREST", "CAMUFLAJE/CAMO FOREST"},
            {"CAMO FOREST", "CAMO FOREST"},
            {"FOREST CAMO", "CAMO FOREST"},
            {"CAMO VERDE", "CAMO FOREST"},

            {"MARRON/NARANJA", "MARRON/NARANJA"},
            {"VERDE/NARANJA", "VERDE/NARANJA"},
            {"VERDE-NARANJA", "VERDE/NARANJA"},
            {"VERDE/NEGRO", "VERDE/NEGRO"},
            {"VEREDE/NEGRO", "VERDE/NEGRO"},
            {"VERDE/NEGRA", "VERDE/NEGRO"},
            {"VERDE/MARRON", "VERDE/MARRON"},
            {"VERDE/ROJO", "VERDE/ROJO"},
            {"MARRON/SEPIA", "MARRON/SEPIA"},
            {"GRIS/VERDE ACIDO", "GRIS/VERDE ACIDO"},
            {"WILLOW GREEN/DEEP BROWN", "WILLOW GREEN/DEEP BROWN"},
            {"GREEN-BROWN", "VERDE/MARRON"},
            {"GREEN-BLAZE", "VERDE/NARANJA"},
            {"NEGRO/ONYX", "NEGRO/ONYX"},
            {"NARANJA,VERDE Y PURPURA", "NARANJA/VERDE/PURPURA"},
            {"CAMUFLAJE/GRIS", "CAMUFLAJE/GRIS"},
            {"CAMUFLAJE/VERDE", "CAMUFLAJE/VERDE"},
            {"CAMO/HI VIS", "CAMO/HI VIS"},

            {"VERDE OLIVA OSCURO", "VERDE OLIVA OSCURO"},
            {"VERDE OLIVA", "VERDE OLIVA"},
            {"OLIVA OSCURO", "VERDE OLIVA OSCURO"},
            {"DARK WARM OLIVE", "VERDE OLIVA OSCURO"},
            {"DARK OLIVE", "VERDE OLIVA OSCURO"},
            {"OLIVA", "VERDE OLIVA"},
            {"OLIVE", "VERDE OLIVA"},

            {"MARRON VERDOSO", "MARRON VERDOSO"},
            {"MARRON-OUTLET", "MARRON"},
            {"DERMITASSE BROWN", "MARRON"},
            {"DARK BROWN", "MARRON"},
            {"DEEP BROWN", "MARRON"},
            {"BROWN", "MARRON"},
            {"MARRON", "MARRON"},

            {"VERDE MILITAR", "VERDE MILITAR"},
            {"VERDE ACIDO", "VERDE ACIDO"},
            {"WILLOW GREEN", "VERDE"},
            {"HUNTING GREEN", "VERDE"},
            {"LODEN", "VERDE"},
            {"GREEN", "VERDE"},
            {"VERDES", "VERDE"},
            {"VERDE", "VERDE"},

            {"HI VIS", "NARANJA"},
            {"HI VI", "NARANJA"},
            {"ALTA VISIBILIDAD", "NARANJA"},
            {"FLUOR", "NARANJA"},
            {"BLAZE", "NARANJA"},
            {"ORANGE", "NARANJA"},
            {"NARANJA", "NARANJA"},

            {"NEGRA", "NEGRO"},
            {"NEGRO", "NEGRO"},
            {"BLACK", "NEGRO"},
            {"ONYX", "NEGRO"},

            {"AMARILLA", "AMARILLO"},
            {"AMARILLO", "AMARILLO"},
            {"YELLOW", "AMARILLO"},

            {"ROSA", "ROSA"},
            {"PINK", "ROSA"},

            {"ROJA", "ROJO"},
            {"ROJO", "ROJO"},
            {"RED", "ROJO"},
            {"ROSSO", "ROJO"},

            {"GRIS", "GRIS"},
            {"GREY", "GRIS"},

            {"AZUL", "AZUL"},
            {"BLUE", "AZUL"},
            {"NAVY", "AZUL MARINO"},

            {"CAMUFLAJE", "CAMUFLAJE"},
            {"CAMO", "CAMO"},

            {"TRASPARENTE", "TRANSPARENTE"},
            {"TRANSPARENTE", "TRANSPARENTE"},
            {"CLEAR", "TRANSPARENTE"},
            {"CLARAS", "TRANSPARENTE"},

            {"PURPURA", "PURPURA"},
            {"PURPLE", "PURPURA"},
            {"MORADO", "MORADO"}
    };

    public  static final String[] MARCAS = {
            "MAGNUM BY BOKER",
            "NATURE BY MARSUPIO",
            "BUFFALO RIVER",
            "NIKKO STIRLING",
            "OPTIK ARMS",
            "KITE OPTICS",
            "BUTLER CREEK",
            "ALAN PAINE",
            "SELLIER BELLOT",
            "SELLIER & BELLOT",
            "FX AIRGUNS",
            "TETRA GUN",
            "TETRA BORE BOA",
            "UNCLE MIKE´S",
            "UNCLE MIKE'S",
            "HOPPE´S",
            "HOPPE'S",
            "B-VISION",
            "B VISION",
            "4 STABLESTICKS",
            "4STABLESTICKS",
            "A-ZOOM",
            "A ZOOM",
            "TRU OIL",
            "MUNDI SOUND",
            "BLACK FIRE",
            "NORTH CO.",
            "NORTH COMPANY",
            "WALKER & HAWKERS",
            "JACK PYKE",
            "JACKE PYKE",
            "HISPANIA HUNTING",
            "HISPANIA",
            "DEL SUR",
            "BASCHIERI & PELLAGRI",
            "BASCHIERI PELLAGRI",
            "BAT VISION",
            "DEAD RINGER",
            "SWISS ARMS",
            "FBT UNIC",
            "POLI NICOLETTA",
            "POLINICOLETTA",
            "OPTIK ARMMS",
            "BUTLER CRREK",
            "SMARTRELOADER",
            "SMART RLOEADED",
            "SEA TO SUMMIT",
            "SEATTOSUMMIT",

            "RTC",
            "MOTIVE",
            "EISPORT",
            "HALTEN",
            "BBI",
            "FAM",
            "MYGRA",
            "CHEDDITE",
            "SORDIN",
            "ARCHER",
            "BEARTOOTH",
            "BEARTOOH",
            "JMG",
            "ONIX",
            "HIVIZ",
            "RUBY",
            "HEIMDAL",
            "CONOTECH",
            "CONTECH",
            "THERMATEC",
            "THERMEYE",
            "ROKSTAD",
            "SABRE",
            "WALKSTOOL",
            "FALCON",
            "ELVEX",
            "SIMOMMS",
            "MANFROTTO",
            "FAB",
            "WEAVER",
            "CORSIVIA",
            "LAPORTE",
            "VECTAN",
            "MANNLINCHER",
            "MANNLICHER",
            "SNOWPEAK",
            "ALBAINOX",
            "LIMBSAVER",
            "ACEBEAM",
            "LEDLENSER",
            "BYRNA",
            "OZKURSAN",
            "LE CHAMEAU",
            "WINCHERSTER",
            "SOLGONE",
            "REMIGTON",
            "STEIBER",
            "BERETTTA",
            "BROWHING",
            "TIIKA",
            "SWAROSKI",
            "PARABELLU",
            "OPLINEL",
            "OLIGTH",
            "OSIGH",
            "VITORINOX",
            "PRIMO",
            "ANCHUTZ",
            "ASTRA",
            "CHAPUIS",
            "MARLIN",
            "BRUNI",
            "FEINWERKAU",
            "HATSAN",
            "HK",
            "SPRINGFIELD",
            "BELLMONTE",
            "ABBEY",
            "ACCUSHARP",
            "AIGLE",
            "AIMPOINT",
            "AIR BOSS",
            "ALPEN",
            "APEL",
            "APOLO",
            "ARCEA",
            "ARMUSA",
            "ATN",
            "AVISTAR",
            "BALLISTOL",
            "BARNAUL",
            "BARNES",
            "BENELLI",
            "BENISPORT",
            "BERETTA",
            "BERGARA",
            "BLASER",
            "BOKER",
            "BORESNAKE",
            "BP",
            "BROWNING",
            "BUCK",
            "BURRIS",
            "BUSHNELL",
            "C16",
            "CANICOM",
            "CASTELLANI",
            "CCI",
            "CHAMPION",
            "CHIRUCA",
            "COMETA",
            "CORZO",
            "CVA",
            "CZ",
            "DEERHUNTER",
            "DEEJO",
            "DELTA",
            "DIOTTO",
            "DOGTRACE",
            "DUNLOP",
            "EUROHUNT",
            "EVOLUTION",
            "EXCOPESA",
            "FABARM",
            "FEDERAL",
            "FIOCCHI",
            "FRANCHI",
            "FULLWAT",
            "FX",
            "GAMO",
            "GARDEPRO",
            "GARMIN",
            "GB",
            "GECO",
            "GERBER",
            "GLOCK",
            "GPO",
            "GUIDE",
            "H&N",
            "HAD",
            "HARKILA",
            "HARRIS",
            "HART",
            "HAWKE",
            "HIKMICRO",
            "HORNADY",
            "HOWA",
            "INFAC",
            "JG",
            "JOLUVI",
            "JSB",
            "KAHLES",
            "KAISER",
            "KESTREL",
            "KITE",
            "KRYTON",
            "LEATHERMAN",
            "LEGIA",
            "LEICA",
            "LEUPOLD",
            "LORPEN",
            "LPA",
            "LZB",
            "MAGTECH",
            "MAGVIEW",
            "MARKHOR",
            "MARKHOUR",
            "MARSUPIO",
            "MAUSER",
            "MDT",
            "MECHANIX",
            "MERKEL",
            "MFS",
            "MIDLAND",
            "MINOX",
            "MORAKNIV",
            "MOSSBERG",
            "MUELA",
            "NATURHUNT",
            "NIGGELOH",
            "NOCPIX",
            "NORICA",
            "NORMA",
            "NORTHWEST",
            "NORTH CO",
            "NOSLER",
            "NUM AXES",
            "ODRA",
            "OKNIFE",
            "OLIGHT",
            "OPINEL",
            "OSIGHT",
            "OTACLE",
            "PARABELLUM",
            "PARD",
            "PELTOR",
            "PERAZZI",
            "PERCUSSION",
            "POLYTEC",
            "PPU",
            "PRIMOS",
            "PULSAR",
            "QUAKE",
            "RECKNAGEL",
            "REMINGTON",
            "RIO",
            "ROLY",
            "RUGER",
            "RUSAN",
            "RWS",
            "SAGA",
            "SAKO",
            "SALAMANDER",
            "SAUVESTRE",
            "SAUER",
            "SAVAGE",
            "SAX",
            "SEATOSUMMIT",
            "SEELAND",
            "SHILBA",
            "SIMMONS",
            "SPARTAN",
            "STEINER",
            "STILCRIN",
            "STINGER",
            "STOEGER",
            "SWAROVSKI",
            "SWEDTEAM",
            "TACTACAM",
            "TAIDEA",
            "TASCO",
            "THERMTEC",
            "TIKKA",
            "TRENTO",
            "TREKSTA",
            "TRIGGERTECH",
            "TRUGLO",
            "TRUST",
            "UMAREX",
            "VALENTO",
            "VANGUARD",
            "VECTOR",
            "VICTORY",
            "VICTORINOX",
            "VIHTAVOURI",
            "VIRUX",
            "VORN",
            "VORTEX",
            "WALTHER",
            "WARNE",
            "WELLGUN",
            "WINCHESTER",
            "YESPORT",
            "ZAMBERLAN",
            "ZEISS",
            "HOPPES",
            "HOPPE",
            "UNCLE MICKE´S",
            "UNCLE MICKE'S",
            "MUNDISOUND",
            "NIKKO",
            "SK",
            "SOLOGNE",
            "WEATHERBY",
            "WBY",
            "CALDWELL",
            "NOBLEX",
            "NIKWAX",
            "MIL-TEC",
            "MILTEC",
            "BITRABI",
            "SPORTDOG",
            "CANIHUNT",
            "WALKER AND HAWKERS",
            "STAGUNT",
            "JOKER",
            "SALAMANDRA",
            "BIRCHWOOD",
            "M-PRO7",
            "FORCE ONE",
            "COAST",
            "TENOSIGHT",
            "DOG TRACE",
            "MONFORT",
            "NEGRINI",
            "SKYWAY",
            "ALPINE",
            "SAFARILAND",
            "VEGA HOLSTER",
            "KNOBLOCH",
            "RADIANS",
            "GRAUVELL",
            "NORDIC GAMEKEEPER",
            "SEEK THERMAL",
            "CHIAPPA",
            "ROSSI",
            "STEYR",
            "LEE",
            "CHEROKY",
            "LUSZCZEK",
            "NICOLETTA",
            "MAVERICK",
            "KRICO",
            "GUERINI",
            "GONHER",
            "MEGALINE",
            "BRESSER",
            "LYMAN",
            "HUNTERNATURE",
            "MOULTRIE",
            "TAGRAC",
            "EOTECH",
            "PACHMAYR",
            "DUELCODE",
            "ALLEN",
            "PROHUNT",
            "NAPIER",
            "SABATTI",
            "SELAND",
            "DEER HUNTER"
    };
    public  static final String[] TALLAS_ROPA = {
            "5XL",
            "4XL",
            "3XL",
            "2XL",
            "XXXL",
            "XXL",
            "XL",
            "2XS",
            "XS",
            "S",
            "M",
            "L",
            "U",
            "UNI",
            "UNICA"
    };

    public  static final String[] TALLAS_NUMERICAS = {
            "34",
            "35",
            "36",
            "37",
            "38",
            "39",
            "40",
            "41",
            "42",
            "43",
            "44",
            "45",
            "46",
            "47",
            "48",
            "49",
            "50",
            "52",
            "54",
            "56",
            "58",
            "60"
    };

    public  static final String[][] CALIBRES = {
            {"CAL 30 06", "30-06"},
            {"30 06", "30-06"},
            {"30-06", "30-06"},

            {"CAL 7MM", "7MM"},
            {"7MM", "7MM"},

            {"CAL 12", "12"},
            {"C 12", "C12"},
            {"C12", "C12"},

            {"CAL 20", "20"},
            {"C 20", "C20"},
            {"C20", "C20"},

            {"CAL 28", "28"},
            {"C 28", "C28"},
            {"C28", "C28"},

            {"C 308", "308"},
            {"CAL 308", "308"},
            {"308", "308"},

            {"270 WSM", "270 WSM"},
            {"300 WSM", "300 WSM"},
            {"300 PRC", "300 PRC"},
            {"300 BLK", "300 BLK"},
            {"300 BLACKOUT", "300 BLACKOUT"},
            {"22 LR", "22 LR"},
            {"22 MAG", "22 MAG"},
            {"17 HMR", "17 HMR"},
            {"22-250", "22-250"},

            {"9.3X74R", "9.3X74R"},
            {"9.3X74", "9.3X74"},
            {"9.3X62", "9.3X62"},
            {"8.5X55", "8.5X55"},
            {"8X68S", "8X68S"},
            {"8X57 JS", "8X57 JS"},
            {"8X57", "8X57"},
            {"7.62X54R", "7.62X54R"},
            {"7.62X54", "7.62X54"},
            {"7.62X39", "7.62X39"},
            {"7X65R", "7X65R"},
            {"7X64", "7X64"},
            {"7X57R", "7X57R"},
            {"7X57", "7X57"},
            {"6.5 CREED", "6.5 CREED"},
            {"6.5 PRC", "6.5 PRC"},
            {"6.5X55", "6.5X55"},
            {"5.5", "5.5"},
            {"5.5MM", "5.5"},
            {"4.5", "4.5"},
            {"4.5MM", "4.5"},
            {"6.35", "6.35"},
            {"6.35MM", "6.35"},
            {"9X19", "9X19"},
            {"9PB", "9PB"},
            {"243", "243"},
            {"270", "270"},
            {"300", "300"},
            {"338", "338"},
            {"357", "357"},
            {"375", "375"},
            {"380", "380"},
            {"410", "410"},
            {"416", "416"},
            {"444", "444"},
            {"460", "460"}
    };

    public  static final String[] TIPOS_ADMITEN_TALLA = {
            "BOTA",
            "BOTAS",
            "ZAPATO",
            "ZAPATILLA",
            "PANTALON",
            "CHAQUETA",
            "CHALECO",
            "CAMISETA",
            "CAMISA",
            "POLO",
            "POLAR",
            "BUZO",
            "GUANTE",
            "GUANTES",
            "GORRA",
            "GORRO",
            "SOMBRERO",
            "CALCETIN",
            "CALCETINES",
            "POLAINA",
            "POLAINAS",
            "CHUBASQUERO",
            "PASAMONTAÑAS",
            "BRAGA",
            "JERSEY",
            "CAMISOLA",
            "SUDADERA",
            "CONJUNTO",
            "FORRO",
            "TRAJE",
            "VADEADOR"
    };

    public  static final String[] TIPOS_ADMITEN_COLOR = {
            "BOTA",
            "BOTAS",
            "ZAPATO",
            "ZAPATILLA",
            "PANTALON",
            "CHAQUETA",
            "CHALECO",
            "CAMISETA",
            "CAMISA",
            "POLO",
            "POLAR",
            "BUZO",
            "GUANTE",
            "GUANTES",
            "GORRA",
            "GORRO",
            "SOMBRERO",
            "CALCETIN",
            "CALCETINES",
            "POLAINA",
            "POLAINAS",
            "CHUBASQUERO",
            "PASAMONTAÑAS",
            "BRAGA",
            "JERSEY",
            "FUNDA",
            "MOCHILA",
            "BOLSA",
            "BOLSO",
            "CORREA",
            "COLLAR",
            "CASCOS",
            "CASCO",
            "GAFAS",
            "MALETIN",
            "MALETA",
            "NAVAJA",
            "CUCHILLO",
            "LENTE",
            "TOALLA",
            "PARAGUAS",
            "AFILADOR",
            "ANILLA",
            "ANILLAS",
            "APOYO",
            "BASE",
            "SOPORTE",
            "ADAPTADOR",
            "ARMERO",
            "COLLAR",
            "CORREA",
            "CUCHILLO",
            "NAVAJA",
            "FUNDA",
            "MOCHILA",
            "BOLSA",
            "MALETA",
            "MALETIN",
            "VISOR",
            "PRISMATICO",
            "BINOCULAR",
            "TRIPODE",
            "ARNES",
            "ASIENTO",
            "BOLA",
            "CANANA",
            "CANTONERA",
            "CULATA"
    };

    public  static final String[] TIPOS_PUEDEN_TENER_CALIBRE = {
            "BALA",
            "BALIN",
            "CARTUCHO",
            "ALIVIAMUELLE",
            "ALIVIAMUELLES",
            "ALIVIAPERCUTOR",
            "ESCOPETA",
            "RIFLE",
            "CARABINA",
            "PISTOLA",
            "REVOLVER",
            "CARGADOR",
            "CHOKE",
            "BAQUETA",
            "PUNTO DE MIRA"
    };
}
